module.exports = {
  _ns: 'zenbot',

  'indicators.ema': require('./ema'),
  'indicators.list[0]': '#indicators.ema',
  'indicators.dema': require('./dema'),
  'indicators.list[1]': '#indicators.dema',
  'indicators.macd': require('./macd'),
  'indicators.list[2]': '#indicators.macd',
  'indicators.typ_price': require('./typ_price'),
  'indicators.list[3]': '#indicators.typ_price',
  'indicators.cci': require('./cci'),
  'indicators.list[4]': '#indicators.cci',
  'indicators.rsi': require('./rsi'),
  'indicators.list[5]': '#indicators.rsi',
  'indicators.stoch_osc': require('./stoch_osc'),
  'indicators.list[6]': '#indicators.stoch_osc',
  'indicators.adx': require('./adx'),
  'indicators.list[7]': '#indicators.adx',
}
